'use strict';
const request=require('supertest');const app=require('../../src/app');const {initializeDatabase,closeDatabase,getDatabase}=require('../../src/config/database');
beforeAll(()=>initializeDatabase());afterAll(()=>closeDatabase());
async function signIn(agent,email,name){await agent.post('/api/v1/auth/request-otp').send({method:'email',identifier:email}).expect(200);return agent.post('/api/v1/auth/verify-otp').send({method:'email',identifier:email,otp:'123456',fullName:name}).expect(200);}
const initiative={title:'Demo Community Safety Session',summary:'A fictional community session used to verify initiative administration safely.',description:'A clearly synthetic initiative record created only by automated CyberShield tests.',organizerName:'CyberShield Demo Content Team',officialSourceUrl:'',category:'training',startDate:'2030-06-10',endDate:'2030-06-11',audience:'Fictional community learners',objectives:'Verify secure content management.',participation:'No real participation is available.',isFeatured:false,isActive:false,isDemo:true,sourceVerifiedAt:null};
describe('initiatives feature',()=>{
 it('lists dated public initiatives and filters statuses',async()=>{const all=await request(app).get('/api/v1/initiatives?limit=10').expect(200);expect(all.body.data.initiatives.length).toBeGreaterThanOrEqual(3);expect(all.body.data.initiatives.every(i=>['upcoming','ongoing','ended'].includes(i.status))).toBe(true);const current=await request(app).get('/api/v1/initiatives?status=ongoing').expect(200);expect(current.body.data.initiatives.every(i=>i.status==='ongoing')).toBe(true);const featured=await request(app).get('/api/v1/initiatives?featured=true&limit=3').expect(200);expect(featured.body.data.initiatives.length).toBeLessThanOrEqual(3);});
 it('protects, validates, creates, edits, audits, and keeps inactive records private',async()=>{await request(app).post('/api/v1/admin/initiatives').send(initiative).expect(401);const user=request.agent(app);await signIn(user,'initiative-user@example.test','Initiative User');await user.post('/api/v1/admin/initiatives').send(initiative).expect(403);const admin=request.agent(app);await signIn(admin,'admin@cybershield.demo','Demo Administrator');await admin.post('/api/v1/admin/initiatives').send({...initiative,officialSourceUrl:'javascript:alert(1)'}).expect(400);const created=await admin.post('/api/v1/admin/initiatives').send(initiative).expect(201);const item=created.body.data.initiative;expect(item.initiativeId).toMatch(/^INI-[A-Z2-9]{8}$/);expect(item).not.toHaveProperty('id');await request(app).get('/api/v1/initiatives/'+item.slug).expect(404);const updated=await admin.patch('/api/v1/admin/initiatives/'+item.initiativeId).send({isActive:true,isFeatured:true}).expect(200);expect(updated.body.data.initiative.isActive).toBe(true);await request(app).get('/api/v1/initiatives/'+item.slug).expect(200);const actions=getDatabase().prepare("SELECT action FROM audit_logs WHERE entity_public_id=? ORDER BY id").all(item.initiativeId).map(row=>row.action);expect(actions).toEqual(expect.arrayContaining(['initiative_created','initiative_updated','initiative_featured','initiative_activated']));});
});
