'use strict';
const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');
const {evidenceConfig}=require('../config/evidence');const shared=require('./evidence.service');const repo=require('../repositories/suspiciousEvidence.repository');const suspiciousRepo=require('../repositories/suspicious.repository');const HttpError=require('../utils/httpError');const {generateSuspiciousEvidenceId,isSuspiciousEvidenceId}=require('../utils/suspiciousIds');
function owned(userId,publicId){const report=suspiciousRepo.findOwned(userId,publicId);if(!report)throw new HttpError(404,'Suspicious report not found.');return report;}
function allocate(){for(let i=0;i<10;i+=1){const id=generateSuspiciousEvidenceId();if(!repo.exists(id))return id;}throw new Error('Unable to allocate evidence ID.');}
async function upload(userId,publicId,files){const report=owned(userId,publicId);if(!['submitted','under_review'].includes(report.status))throw new HttpError(409,'Evidence cannot be added in this report status.');const config=evidenceConfig();if(!files.length||repo.count(report.id)+files.length>config.maxFiles)throw new HttpError(400,'Maximum evidence limit reached.');const validated=[];for(const file of files)validated.push(await shared.validateFile(file));const createdAt=new Date().toISOString();const records=validated.map(f=>({...f,evidenceId:allocate(),reportId:report.id,storedFilename:`${crypto.randomUUID()}.${f.fileExtension}`,uploadStatus:'accepted',createdAt}));const paths=[];try{for(const record of records){const destination=path.join(config.storagePath,record.storedFilename);await fs.promises.writeFile(destination,record.buffer,{flag:'wx',mode:0o600});paths.push(destination);delete record.buffer;}repo.insertMany(records,config.maxFiles);}catch(error){await Promise.all(paths.map(p=>fs.promises.unlink(p).catch(()=>{})));if(error.code==='EVIDENCE_LIMIT_REACHED')throw new HttpError(400,'Maximum evidence limit reached.');throw error;}return records.map(shared.publicEvidence);}
function list(userId,publicId){const report=owned(userId,publicId);return suspiciousRepo.evidenceFor(report.id).map(shared.publicEvidence);}
function fileFor(reportId,evidenceId,ownerId){const report=ownerId?owned(ownerId,reportId):suspiciousRepo.findByPublicId(reportId);if(!report||!isSuspiciousEvidenceId(evidenceId))return null;const evidence=repo.find(report.id,evidenceId.toUpperCase());if(!evidence)return null;const filePath=path.join(evidenceConfig().storagePath,evidence.stored_filename);return fs.existsSync(filePath)?{evidence,filePath}:null;}
module.exports={fileFor,list,upload};
